### ISSUE TITLE
Use GitHub Pages to render page in more stable format

### ISSUE THREAD

**Issue by cmccandless** [viatsko/awesome-vscode#123]
Due to the large number of images and the general large size of the README file, clicking links in the Table of Contents does not always navigate cleanly. Simply turning on GitHub Pages on the master branch and applying a theme would make this list more stable and readable.

**Comment by viatsko** [comment]
Hi, I've started to work on it, but something didn't go well https://viatsko.github.io/awesome-vscode/

I'll try to find some time this week to work on GH page

**Comment by cmccandless** [comment]
I suspect that the markdown parser used by GitHub pages will not parse text as markdown if it's wrapped in HTML. If that is indeed the case, either extract all markdown from any HTML blocks, or convert the embedded markdown to HTML.

**Comment by cmccandless** [comment]
Resolved! Thanks for the update @jschr
