### ISSUE TITLE
The extension "Copy relative path" is not need after version 1.26 of the editor

### ISSUE THREAD

**Issue by in-in** [viatsko/awesome-vscode#166]
There is built-in hotkey for Copy Relative Path task `Ctrl+Shift+Alt+C` and it is also available in the context menu.
https://code.visualstudio.com/updates/v1_26#_copy-relative-path

**Comment by KamilOcean** [comment]
Yeah, I agree with You. It should be marked as a deprecated extension or removed.

**Comment by lannonbr** [comment]
Given 1.26 has been out for a few months, I think removing the extension from the list would be a good decision since it is just native to VS Code now. Feel free to submit a PR @in-in 😄

**Comment by lannonbr** [comment]
Done in #171. Closing
