### ISSUE TITLE
Vim extension shhould be moved to "Editor Keymaps"

### ISSUE THREAD

**Issue by mr-ubik** [viatsko/awesome-vscode#168]
Is there any reason why the Vim Extension is not together with the other keymaps packs?

**Comment by lannonbr** [comment]
It looks like the VSCode Vim extension is more trying to emulate Vim in VS Code while the keymaps for Atom, IntelliJ, etc. are just keymaps with no other features, so I do see a difference between them. If we were to move this package up with the other keymaps, the current category header of "Editor Keymaps" would be a little misleading given VSCodeVim does a lot more than just rebinding keys.

@jschr & @viatsko, do you two have any opinions on this?

**Comment by jschr** [comment]
In terms of discoverability, it's more likely for someone to look for Vim (or a Vim-related extension) in keymaps. In general, I think we should strive to make a few items "Uncategorized" as possible to make the list easier to discover. 

The Vim extension does do more than keymaps but perhaps the section title could be "Migrating from other editors" to be more inline with the sub-sections in that category. Moving Vim there would make sense to me in that case. 

@mr-ubik are you up for making a PR with this change? We can continue the discussion from there.

**Comment by brunofontes** [comment]
I am no one here, but if I could give my 2 cents, I would say to try keep the Vim plugin near the Keymaps category, even if it stays in a separate category. So you can keep your organization, but it would still be easy to find.

**Comment by mr-ubik** [comment]
@jschr I will write it asap
