### ISSUE TITLE
Adding Octobox Github App to awesome-vscode repo

### ISSUE THREAD

**Issue by lannonbr** [viatsko/awesome-vscode#191]
I use [Octobox](https://octobox.io/) to keep track of my notifications from Github and I think it would be useful to add their [Github plugin](https://github.com/apps/octobox) to this repo. It adds tags & colors to issue / PR statuses.

This is currently how it looks for this repo looks on Octobox:

![screen shot 2018-10-10 at 9 16 00 am](https://user-images.githubusercontent.com/3685876/46738893-4a02d000-cc6d-11e8-8080-0386a1f1714a.png)

**Comment by lannonbr** [comment]
No, this isn’t something I wanted to add to the list but rather have Octobox have access to the repo. It’s more infrastructure and not something that is being added to the list

**Comment by duttaditya18** [comment]
@lannonbr I see! I am sorry for not understanding.

**Comment by viatsko** [comment]
Makes sense. Thanks, added! :)
