### ISSUE TITLE
Create your settings and extensions with extension Settings Sync

### ISSUE THREAD

**Issue by shanalikhan** [viatsko/awesome-vscode#30]
Hi, 
This is not a bug but its a suggestion. You can share your customized code settings including extensions with users and users can download those settings, anytime you change the settings. Users code environment will be updated in terms of extensions and settings.

Try with Code "Settings Sync" extension
Share the settings with giving customized Gist of  extensions for designers , developers etc.

http://shanalikhan.github.io/2016/09/02/how-to-Share-visual-studio-code-settings.html

**Comment by viatsko** [comment]
Hi, thanks. I'll take a look. However, I think, that this idea is a bit outside of this curated list's scope.
