### ISSUE TITLE
highlight html opening or closing of tag depending on which end you have the cursor on

### ISSUE THREAD

**Issue by turtuga** [viatsko/awesome-vscode#34]
Hello 

first thanks for your work 

I saw this in one of yours images how i do this
https://raw.githubusercontent.com/formulahendry/vscode-auto-rename-tag/master/images/usage.gif

**Comment by SamVerschueren** [comment]
By clicking the link associated with the picture and installing that extension: https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag

**Comment by turtuga** [comment]
Thanks but this only rename tags not highlight open or close tag like cursor goes second time to div

**Comment by SamVerschueren** [comment]
Highlighting of html tags is automatically done by VS Code and has nothing to do with the extension. I don't have the extension installed and it still highlights them.

<img width="260" alt="screen shot 2017-01-27 at 20 18 30" src="https://cloud.githubusercontent.com/assets/1913805/22384275/d922361a-e4cd-11e6-9bd2-bdc770177937.png">

If that's not the case for you I suggest opening an issue in the official VS Code repository or try changing your VS Code theme first. Might have something to do with that.

**Comment by turtuga** [comment]
You are right on PHP this not work highlight all divs :( big thanks for your time
