### ISSUE TITLE
Rust plugin depreciated

### ISSUE THREAD

**Issue by MrMcEpic** [viatsko/awesome-vscode#387]
The currently recommended Rust plugin https://marketplace.visualstudio.com/items?itemName=rust-lang.rust has been depreciated.

Switch the recommended Rust plugin to the new official Rust-Analyzer https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer

**Comment by matifali** [comment]
After #391 is merged. This issue should be closed.
