### ISSUE TITLE
XO

### ISSUE THREAD

**Issue by SamVerschueren** [viatsko/awesome-vscode#4]
I've build an extension to use the [XO](https://github.com/sindresorhus/xo) linter from @sindresorhus. Would you be willing to accept a PR to add it to the list or not?

**Comment by viatsko** [comment]
I like it :)

**Comment by viatsko** [comment]
I don't think eslint is the only and ultimate choice, I am using multiple js linters myself

**Comment by SamVerschueren** [comment]
At the moment it's quite hard to see where I should insert a link to the plugin as it doesn't follow the exact same style as other awesome lists (like [awesome-nodejs](https://github.com/sindresorhus/awesome-nodejs) for example).

Maybe subdivide things under `Lint and IntelliSense`? Something like this.

## Lint and IntelliSense

### C++

- [gnu-global-tags](https://marketplace.visualstudio.com/items?itemName=austin.code-gnu-global) - Provide Intellisense for C/C++ with the help of the GNU Global tool.

### CSS

- [stylelint](https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint) - Lint CSS/SCSS.

### Go

- [Go](https://marketplace.visualstudio.com/items?itemName=lukehoban.Go) - Rich language support for the Go language.

### JavaScript

- [eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) - Linter for [eslint](http://eslint.org/).
- [XO](https://marketplace.visualstudio.com/items?itemName=samverschueren.linter-xo) - Linter for [XO](https://github.com/sindresorhus/xo)

### Python

- [Pythong](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) - Linting, Debugging (multi threaded, web apps), Intellisense, auto-completion, code formatting, snippets, unit testing, and more.

This would make it easier of other people want to submit language specific linters/intellisense packages.

**Comment by viatsko** [comment]
I think that syntax and linters should be merged (looking and go package for example) and yes, I like your formatting

**Comment by viatsko** [comment]
*at go, damn autocomplete on iphone :)
