### ISSUE TITLE
Library section

### ISSUE THREAD

**Issue by SamVerschueren** [viatsko/awesome-vscode#7]
Are you in for creating a section regarding libraries for VS Code extensions?

For example, I created a [vscode-set-text](https://github.com/samverschueren/vscode-set-text) extension that makes it easier to set text in a `TextEditor`. Related to [atom-set-text](https://github.com/sindresorhus/atom-set-text).

Might be interesting for extension developers.

**Comment by viatsko** [comment]
That's a very interesting suggestion and I'd for sure like to have it for Atom as Atom's packages developer also.

Do we have examples of awesome- repositories including resources of this type?

**Comment by SamVerschueren** [comment]
I looked in the [awesome](https://github.com/sindresorhus/awesome) list but it seems not (that I'm aware of at least :)).

**Comment by viatsko** [comment]
https://github.com/viatsko/awesome-vscode/commit/117341a4ad783483281006542dfd365e94867cc5

?

**Comment by SamVerschueren** [comment]
We might even create an `awesome-vscode-modules` repo only for such libraries/modules. Not sure which one I prefer most.

**Comment by viatsko** [comment]
I'd prefer the current approach (without split), I'm not sure we'll have big audience in this repository even after approval to main awesome :P

**Comment by SamVerschueren** [comment]
Good point. We can always split up later if we want :).

**Comment by SamVerschueren** [comment]
What should be added to this section?

- Yeoman generator (yo code)
- Link to the extension development docs? ([this one](https://code.visualstudio.com/docs/extensions/overview))

what else?

**Comment by viatsko** [comment]
Those are enough for now :+1:
