### ISSUE TITLE
New VS Code Icon

### ISSUE THREAD

**Issue by viatsko** [viatsko/awesome-vscode#76]
Stable VS Code just release with a new icon, see https://github.com/Microsoft/vscode/issues/6607#issuecomment-324456824

Would be great to change the icon in this repository as well (probably adding awesome glasses too?)

**Comment by Yliaho** [comment]
How's this? https://github.com/viatsko/awesome-vscode/pull/78

**Comment by viatsko** [comment]
Exceeds any expectations :) Thanks a lot!

**Comment by yliaho** [comment]
Guess the icon needs a new update again soon 😛  
  
https://code.visualstudio.com/blogs/2017/10/24/theicon
