### ISSUE TITLE
Shouldn't the image represent the new logo?

### ISSUE THREAD

**Issue by asamolion** [viatsko/awesome-vscode#91]
The new logo is blue again now, so shouldn't it be blue as well?

[new logo](https://github.com/asamolion/awesome-vscode/blob/master/awesome-vscode-logo.png)

**Comment by asamolion** [comment]
https://github.com/viatsko/awesome-vscode/pull/92

**Comment by viatsko** [comment]
Thanks, it should! We are a bit behind the updates as it's often not clear if change is implemented from VS Code side speaking about the logo :)
